name: track_my_indoor_exercise
description: Recording indoor exercises as if circling on a track.
publish_to: "none"

version: 2.0.160+160
isar_version: &isar_version ^3.1.8

environment:
  sdk: ">=3.7.0"
  flutter: ">=3.29.0"

dependency_overrides:
  analyzer: ^7.3.0 # isar community

dependencies:
  app_links: ^6.3.3
  assorted_layout_widgets: ^11.0.0
  audioplayers: ^6.1.2
  collection: ^1.19.1
  datetime_picker_formfield_new: ^2.1.0
  device_info_plus: ^11.3.0
  edit_distance: ^0.5.0-nullsafety.0
  email_validator: ^3.0.0
  expandable: ^5.0.1
  fab_circular_menu_plus: ^0.0.3
  file_picker: ^8.3.7
  flex_color_scheme: ^8.1.0
  flutter_archive: ^6.0.3
  flutter_blue_plus: ^1.35.2
  flutter_circle_color_picker: ^0.3.0
  flutter_layout_grid: ^2.0.7
  flutter_spinbox: ^0.13.1
  flutter_svg: ^2.0.17
  flutter_timezone: ^4.1.0
  get: ^4.7.2
  group_button: ^5.3.4
  http: ^1.3.0
  http_parser: ^4.1.2
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.20.2
  is_first_run: ^1.0.0
  isar:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  listview_utils_plus: ^0.0.4
  loading_overlay: ^0.4.2
  number_selector: ^1.0.7
  package_info_plus: ^8.2.1
  path: ^1.9.1
  path_provider: ^2.1.5
  pref: ^2.8.0
  progress_indicators: ^1.0.0
  qr_widget: ^4.1.0
  rxdart: ^0.28.0
  receive_sharing_intent: ^1.8.1
  share_plus: ^10.1.4
  string_validator: ^1.1.0
  syncfusion_flutter_charts: ^28.2.5+1
  timezone: ^0.10.0
  tuple: ^2.0.2
  url_launcher: ^6.3.1
  vector_math: ^2.1.4
  wakelock_plus: ^1.2.10
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: ^7.3.0
  build_runner: ^2.4.15
  flutter_driver:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  mocktail: ^1.0.4
  mock_data: ^2.0.1
  yaml: ^3.1.3

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
    - family: brands
      fonts:
        - asset: fonts/brands.ttf
  assets:
    - assets/
    - assets/audio/
    - assets/donation/
    - assets/integration/
    - assets/equipment/
#  plugin:
#    platforms:
#      android:
#        package: heart_rate_flutter
#        pluginClass: HeartRateFlutter
