name: track_my_indoor_exercise
description: Recording indoor exercises as if circling on a track.
publish_to: "none"

version: 1.1.146+146

environment:
  sdk: ">=2.23.1"
  flutter: ">=3.10.0-1.1.pre"

dependency_overrides:
  win32: 3.1.4

dependencies:
  assorted_layout_widgets: ^8.0.4
  bluetooth_enable_fork: ^0.1.6
  collection: ^1.17.2
  datetime_picker_formfield_new: ^2.1.0
  device_info_plus: ^9.0.2
  easy_folder_picker: ^1.3.0
  edit_distance: ^0.5.0-nullsafety.0
  expandable: ^5.0.1
  file_picker: ^5.3.2
  flex_color_scheme: ^7.1.2
  floor: ^1.4.2
  flutter_blue_plus: ^1.5.2
  flutter_circle_color_picker: ^0.3.0
  flutter_layout_grid: ^2.0.4
  flutter_logs:
    git:
      url: https://github.com/CsabaConsulting/flutter_logs.git
  flutter_spinbox: ^0.13.1
  flutter_svg: ^2.0.7
  flutter_timezone: ^1.0.7
  get: ^4.6.1
  group_button: ^5.3.0
  http: ^0.13.6
  http_parser: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  listview_utils: ^1.0.0-nullsafety
  loading_overlay: ^0.3.0
  number_selector: ^1.0.7
  package_info_plus: ^4.0.2
  path: ^1.8.2
  path_provider: ^2.0.15
  pref: ^2.7.1
  progress_indicators: ^1.0.0
  qr_widget: ^4.1.0
  rxdart: ^0.27.7
  share_files_and_screenshot_widgets: ^1.0.6
  soundpool: ^2.3.0
  sqflite: ^2.2.8+4
  string_validator: ^1.0.0
  syncfusion_flutter_charts: ^22.1.37
  timezone: ^0.9.2
  tuple: ^2.0.2
  uni_links: ^0.5.1
  url_launcher: ^6.1.11
  vector_math: ^2.1.4
  wakelock: ^0.6.2
  flutter:
    sdk: flutter

dev_dependencies:
  analyzer: ^5.13.0
  build_runner: ^2.4.6
  floor_generator: ^1.4.2
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.2
  mock_data: ^2.0.0
  yaml: ^3.1.2

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
    - family: brands
      fonts:
        - asset: fonts/brands.ttf
  assets:
    - assets/
    - assets/audio/
    - assets/donation/
    - assets/integration/
    - assets/equipment/
